name: Generate Datas

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  
jobs:
  bild:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
    
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: gabrielaaura
          svg_out_path: dist/github-contribution-grid-snake.svg
      
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          buil_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
